src/main/java/info/touret/mwc/gui/BottleManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package info.touret.mwc.gui;

import info.touret.mwc.gui.util.ViewScoped;
import info.touret.mwc.model.Bottle;
import info.touret.mwc.model.Producer;
import info.touret.mwc.model.Tag;
import info.touret.mwc.service.BottleService;
import info.touret.mwc.service.BusinessService;
import info.touret.mwc.service.ProducerService;
import info.touret.mwc.service.TagService;

import javax.ejb.EJB;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * @author touret-a
 */
@Named("bottleManagedBean")
@ViewScoped
public class BottleManagedBean extends CRUDManagedBean<Bottle> {

    @EJB
    BottleService bottleservice;
    @EJB
    ProducerService producerService;
    @EJB
    TagService tagService;

    private List<Producer> producers;

    public List<Producer> getProducers() {
        if (producers == null) {
            setProducers(producerService.list(Producer.class));
        }
        return producers;
    }

    public void setProducers(List<Producer> producers) {
        this.producers = producers;
    }

    private Producer selectProducer;

    public Producer getSelectProducer() {
        return selectProducer;
    }

    private Integer selectProducerId;

    public Integer getSelectProducerId() {
        return selectProducerId;
    }

    public void setSelectProducerId(Integer selectProducerId) {
        this.selectProducerId = selectProducerId;
    }

    public void setSelectProducer(Producer _selectProducer) {
        this.selectProducer = _selectProducer;
    }

    private List<SelectItem> producerItems;

    public List<SelectItem> getProducerItems() {
        if (producerItems == null) {
            producerItems = new ArrayList<SelectItem>();
            for (Producer current : getProducers()) {
                producerItems.add(new SelectItem(current.getId(), current.getName()));
            }
        }
        return producerItems;
    }

    public void setProducerItems(List<SelectItem> producerItems) {
        this.producerItems = producerItems;
    }

    public List<Tag> getAllTags() {
        List<Tag> tags = new ArrayList<Tag>();
        tags = tagService.list(Tag.class);
        return tags;
    }


    @Override
    protected Bottle newInstance() {
        return new Bottle();
    }

    @Override
    protected String url() {
        return "/faces/bottlemgmt";
    }

    @Override
    protected String getEntityDescription() {
        return "La bouteille " + getEntity().getName();
    }

    @Override
    protected BusinessService<Bottle> getService() {
        return bottleservice;
    }

    @Override
    protected Class<Bottle> getDomainClass() {
        return Bottle.class;
    }

    public List<Producer> searchProducers(String query) {
        Producer p = new Producer();
        p.setName(query);
        return producerService.findLikeBySelectedAttributes(Producer.class, p, "name");
    }

    @Override
    public void saveNew(javax.faces.event.ActionEvent event) {
        getEntity().setProducer(producerService.findByID(Producer.class, getSelectProducerId()));
        super.saveNew(event);
    }

    @Deprecated
    public String getGoogleCalendarLink() {
        String originalLink = "http://www.google.com/calendar/event?action=TEMPLATE&text=@@TEXTE@@&dates=@@DATE@@/@@DATE@@&details=&location=&trp=false&sprop=my-wine-cellar.touret.info&sprop=name:my%20wine%20cellar";
        String link = originalLink.replace("@@TEXTE@@", getEntity().getName());
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
        String date = format.format(getEntity().getTodrink());
        link = link.replace("@@DATE@@", date);
        return link;
    }

    @Override
    protected String[] getFilterColumns() {
        return new String[]{"name", "denomination"};
    }

    @Override
    protected Bottle getDefaultDomainObject() {
        return new Bottle();
    }

    @Override
    public Bottle getEntity() {
        Bottle bottle = super.getEntity();
        if (bottle.getVintage() == 0) {
            bottle.setVintage(GregorianCalendar.getInstance().get(Calendar.YEAR));
            bottle.setAcquired(new Date());
        }
        return bottle;
    }
}

src/main/java/info/touret/mwc/gui/DashBoardManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package info.touret.mwc.gui;

import com.google.common.base.Function;
import info.touret.mwc.model.Bottle;
import info.touret.mwc.model.DateInterval;
import info.touret.mwc.model.Tag;
import info.touret.mwc.model.Tasting;
import info.touret.mwc.service.BottleService;
import info.touret.mwc.service.TagService;
import info.touret.mwc.service.TastingService;
import org.primefaces.model.DashboardColumn;
import org.primefaces.model.DashboardModel;
import org.primefaces.model.DefaultDashboardColumn;
import org.primefaces.model.DefaultDashboardModel;
import org.primefaces.model.chart.DonutChartModel;
import org.primefaces.model.chart.PieChartModel;
import org.primefaces.model.tagcloud.DefaultTagCloudItem;
import org.primefaces.model.tagcloud.DefaultTagCloudModel;
import org.primefaces.model.tagcloud.TagCloudModel;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

/**
 * @author touret-a
 */
@Named("dashboardManagedBean")
@RequestScoped
public class DashBoardManagedBean {

    private DashboardModel boardModel;

    private final static Logger trace = Logger.getLogger(DashBoardManagedBean.class.getCanonicalName());

    public DashboardModel getBoardModel() {
        if (boardModel == null) {
            setBoardModel(new DefaultDashboardModel());
            DashboardColumn column1 = new DefaultDashboardColumn();
            DashboardColumn column2 = new DefaultDashboardColumn();
            column1.addWidget("aide");
            column1.addWidget("calendar");
            column2.addWidget("yearchart");
            column2.addWidget("tagchart");
            boardModel.addColumn(column1);
            boardModel.addColumn(column2);
        }
        return boardModel;
    }

    public void setBoardModel(DashboardModel boardModel) {
        this.boardModel = boardModel;
    }

    @EJB
    private BottleService bottleService;
    private List<Bottle> bottles;
    @EJB
    private TagService tagService;

    @EJB
    private TastingService tastingService;

    public List<Bottle> getBottles() {
        if (bottles == null) {
            setBottles(bottleService.getBottleList());
        }
        return bottles;
    }

    public void setBottles(List<Bottle> bottles) {
        this.bottles = bottles;
    }


    public DashBoardManagedBean() {
        super();
    }

    private List<Bottle> nextBottlesToDrink;

    public List<Bottle> getNextBottlesToDrink() {
        if (nextBottlesToDrink == null) {
            setNextBottlesToDrink(bottleService.findBottlesDrunkByDate(DateInterval.getNextMonths(6)));
        }
        return nextBottlesToDrink;
    }

    public void setNextBottlesToDrink(List<Bottle> nextBottlesToDrink) {
        this.nextBottlesToDrink = nextBottlesToDrink;
    }

    private PieChartModel bottleCountByYear;

    public PieChartModel getBottleCountByYear() {
        if (bottleCountByYear == null) {
            Map<String, Number> bottleMap = new HashMap<String, Number>(getBottles().size());
            for (Bottle current : getBottles()) {
                if (bottleMap.get(current.getVintage()) == null) {
                    bottleMap.put(String.valueOf(current.getVintage()), current.getQuantity());
                } else {
                    Number by = bottleMap.get(String.valueOf(current.getVintage()));
                    by = by.intValue() + current.getQuantity();
                    bottleMap.put(String.valueOf(current.getVintage()), by);
                }

            }
            setBottleCountByYear(new PieChartModel(bottleMap));
        }
        return bottleCountByYear;
    }

    public void setBottleCountByYear(PieChartModel _bottleCountByYear) {
        this.bottleCountByYear = _bottleCountByYear;
    }


    public DonutChartModel getAllTagsModel() {
        DonutChartModel model = new DonutChartModel();
        Map<String, Number> circle = new HashMap();
        Map<String, Tag> tags = tagService.getIndexedTags();
        for (String current : tags.keySet()) {
            circle.put(current, tags.get(current).getWeight());
        }

        model.addCircle(circle);
        return model;
    }

    public TagCloudModel getTagCloudModel() {
        TagCloudModel model = new DefaultTagCloudModel();
        Map<String, Tag> tags = tagService.getIndexedTags();
        for (String current : tags.keySet()) {
            model.addTag(new DefaultTagCloudItem(current, "#", getTagStrength(tags.get(current))));
        }
        model.addTag(new DefaultTagCloudItem("TESTCLOUD", 110));
        return model;
    }

    private Integer getTagStrength(Tag tag) {
        Function<Tag, Integer> tagFunction = new Function<Tag, Integer>() {
            @Override
            public Integer apply(Tag input) {
                Integer strength = new Integer(1);
                if (input.getWeight() >= 2) {
                    strength = 2;
                } else {
                    if (input.getWeight() >= 5) {
                        strength = 3;
                    } else {
                        if (input.getWeight() >= 10) {
                            strength = 4;
                        } else {
                            if (input.getWeight() >= 20) {
                                strength = 5;
                            }
                        }
                    }
                }
                return strength;
            }
        };
        return tagFunction.apply(tag);
    }


    private List<Tasting> lastTasted;

    public List<Tasting> getLastTasted() {
        if (lastTasted == null) {
            lastTasted = tastingService.getLastTastings(DateInterval.getLastMonths(6));
        }
        return lastTasted;
    }

    public void setLastTasted(List<Tasting> lastTasted) {
        this.lastTasted = lastTasted;
    }

    private List<Tasting> bestTastings;

    public List<Tasting> getBestTastings() {
        if (bestTastings == null) {
            setBestTastings(tastingService.getBestTastings(10));
        }
        return bestTastings;
    }

    public void setBestTastings(List<Tasting> bestTastings) {
        this.bestTastings = bestTastings;
    }


}


src/main/java/info/touret/mwc/gui/UserManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package info.touret.mwc.gui;


import info.touret.mwc.model.UserWine;
import info.touret.mwc.service.BusinessService;
import info.touret.mwc.util.Logged;
import info.touret.mwc.util.UserWineAccount;
import info.touret.mwc.util.UserWineNotFoundException;
import info.touret.mwc.util.UserWineWrapper;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.io.Serializable;
import java.util.*;
import java.util.logging.Logger;

/**
 * Managed bean gerant l identification
 *
 * @author touret-a
 */
@Named("userManagedBean")
@SessionScoped
public class UserManagedBean implements Serializable {

    @Inject
    private ApplicationManagedBean applicationManagedBean;

    public UserManagedBean() {
    }

    @Inject
    UserWineWrapper userWineWrapper;

    private UserWine user;

    public UserWine getUser() {
        if (user == null) {
            setUser(createUserWine());
        }
        return user;
    }

    /**
     * gere le retour a la page d identification
     */
    private void goToLogin() {
        try {
            ((HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse()).sendRedirect(applicationManagedBean.getBaseUrl().concat("/faces/login.xhtml"));
        } catch (IOException e) {
        }
    }


    /**
     * Cree un utilisateur de type UserWine a partir du retour de l identification google et le met en cache
     *
     * @return l utilisateur
     */
    @Logged
    @Produces
    public UserWine createUserWine() {
        UserWine userWine = null;
        if (user == null) {
            userWine = new UserWine();
            trace.fine("Creation instance user");
            HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
            if (session == null) {
                goToLogin();
            }
            UserWineAccount userWineAccount = (UserWineAccount) session.getAttribute("login_account");
            trace.info("Utilisateur retourne par GIT :" + userWineAccount);
            if (userWineAccount == null) {
                // erreur, la session n existe pas ! retour identification
                goToLogin();
            }
            try {
                userWine = userWineWrapper.setAccount(userWineAccount).toUserWine();
            } catch (UserWineNotFoundException e) {
                goToLogin();
            }
            setUser(userWine);
        } else {
            userWine = user;
        }
        trace.fine("USER GENERE PAR CDI : " + userWine);
        return userWine;
    }

    @Inject
    private BusinessService<UserWine> service;

    private final static Logger trace = Logger.getLogger(UserManagedBean.class.getName());

    /**
     * Initialise les utilisateurs
     *
     * @param _user
     */
    public void setUser(UserWine _user) {
        this.user = _user;
    }

    /**
     * retourne la requete d autorisation pour la gestion du calendrier google
     *
     * @return la locale
     */
    public Locale getCurrentLocale() {
        return FacesContext.getCurrentInstance().getExternalContext().getRequestLocale();
    }

    /**
     * Retourne le message
     *
     * @param severity
     * @param shortMessage
     * @param longMessage
     * @param messageParams
     * @return
     */
    public FacesMessage getMessage(FacesMessage.Severity severity, String shortMessage, String longMessage, Object... messageParams) {
        return new FacesMessage(severity,
                getMessage(shortMessage, getCurrentLocale(), messageParams),
                getMessage(longMessage, getCurrentLocale(), messageParams));
    }


    /**
     * retourne un message donne
     *
     * @param message
     * @param locale
     * @param params
     */
    public String getMessage(String message, Locale locale, Object... params) {
        String newmessage = "";
        ResourceBundle bundle = ResourceBundle.getBundle("messages", locale);
        Set<String> keys = bundle.keySet();
        message = bundle.getString(message);
        int i = 0;
        for (String current : keys) {
            newmessage = newmessage.replace(current, params[i++].toString());
            if (i >= params.length) {
                break;
            }
        }
        return newmessage;
    }

    /**
     * Retourne le minimum
     */
    public Integer getMinBottleYear() {
        Calendar cal = GregorianCalendar.getInstance(getCurrentLocale());
        return cal.get(Calendar.YEAR) - 30;
    }

    /**
     * Retourne le max
     */
    public Integer getMaxBottleYear() {
        Calendar cal = GregorianCalendar.getInstance(getCurrentLocale());
        return cal.get(Calendar.YEAR);
    }

    public void logout(ActionEvent event) {
        ((HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false)).invalidate();
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        session = null;
    }

}

src/main/webapp/protected/bottlemgmt.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<body>
<ui:composition template="standardtpl.xhtml">
<ui:define name="content">
    <h:form prependId="false" id="bottlemgmt_form">
        <f:event type="javax.faces.event.PreRenderViewEvent" listener="#{bottleManagedBean.preRenderView}"/>
        <p:growl id="growl"/>
        <p:tabView>

            <p:tab title="#{messages.bottleaddheader}"
                   id="addBottlePanel">
                <h:panelGrid columns="2" id="addBottlePanelGrid">
                    <f:validateBean>
                        <h:outputLabel value="#{messages.bottlenamelabel}" id="labelnomb"/><p:inputText
                            id="inputnameb" value="#{bottleManagedBean.entity.name}"
                            validatorMessage="#{messages.bottleaddinvalidname}" styleClass="custom-class"/>
                        <h:outputLabel value="#{messages.bottleproducerlabel}" id="labelprodocteurb"/>

                        <p:selectOneMenu value="#{bottleManagedBean.selectProducerId}" panelStyle="width:150px"
                                         effect="fade" style="width: 180px"
                                         id="selectproducerb" filter="true" filterMatchMode="contains">
                            <f:selectItem itemLabel="" itemValue=""/>
                            <f:selectItems value="#{bottleManagedBean.producerItems}"/>
                        </p:selectOneMenu>
                        <h:outputLabel value="#{messages.bottlequantitylabel}" id="quantiteb"/> <p:spinner
                            value="#{bottleManagedBean.entity.quantity}"
                            validatorMessage="#{messages.bottleaddinvalidquantity}" showOn="hover"
                            />
                        <h:outputLabel value="#{messages.bottletodrinklabel}" id="todrinkb"/> <p:calendar
                            value="#{bottleManagedBean.entity.todrink}" style="text-align: right"
                            validatorMessage="#{messages.bottleaddinvalidtodrink}" pages="3"
                            />
                        <h:outputLabel value="#{messages.bottleboughtlabel}" id="dateachatb"/> <p:calendar
                            value="#{bottleManagedBean.entity.acquired}" style="text-align: right"
                            validatorMessage="#{messages.bottleaddinvalidacquired}" pages="3"/>
                        <h:outputLabel value="#{messages.bottlevintagelabel}" id="vintageb"/> <p:spinner
                            value="#{bottleManagedBean.entity.vintage}"
                            showOn="hover" max="#{userManagedBean.maxBottleYear}"
                            min="#{userManagedBean.minBottleYear}"
                            validatorMessage="#{messages.bottleaddinvalidvintage}"/>
                        <h:outputLabel value="#{messages.bottletagslabel}" id="tagsb"/>
                        <p:inputText value="#{bottleManagedBean.entity.tags}" converter="#{tagConverter}">

                        </p:inputText>


                    </f:validateBean>
                    <p:commandButton value="#{messages.submit}"
                                     actionListener="#{bottleManagedBean.saveNew}"
                                     label="#{messages.submit}"
                                     update="@form"
                            />
                    <p:commandButton value="#{messages.cancel}"
                                     action="#{bottleManagedBean.resetNew}"
                                     update="@form"
                                     label="#{messages.cancel}"/>
                </h:panelGrid>
            </p:tab>

            <p:tab title="#{messages.bottlelistheader}" id="bottlesListPanel">
                <h:panelGrid columns="2" id="bottlePanelGrid" cellpadding="5">
                    <h:panelGroup>
                        <p:dataTable var="currentBottle"
                                     value="#{bottleManagedBean.entities}"
                                     emptyMessage="#{messages.standardemptytable}"
                                     selection="#{bottleManagedBean.entityTableSelection}"
                                     selectionMode="single"
                                     paginator="true"
                                     paginatorPosition="bottom"
                                     rows="10"
                                     rowKey="#{currentBottle.id}"
                                     id="bottleDataTable"
                                     widgetVar="bottlesWidgetVar"
                                     editable="true"
                                     filteredValue="#{bottleManagedBean.filteredEntities}"
                                     filterEvent="keyup">
                            <p:ajax event="rowEdit" listener="#{bottleManagedBean.updateCurrent}" update="@this"
                                    async="true"/>

                            <f:facet name="header">
                                <p:outputPanel style="text-align: right">
                                    <h:outputText value="#{messages.searchtextlabel}" style="padding-right: 2px"/>
                                    <p:inputText id="globalfilter" value="#{bottleManagedBean.filter}"
                                                 onkeyup="bottlesWidgetVar.filter()" style="width:150px">
                                    </p:inputText>

                                </p:outputPanel>
                            </f:facet>
                            <p:column sortBy="#{currentBottle.name}"
                                      filterBy="#{currentBottle.name}"
                                      filterStyle="width: 80%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottlenamelabel}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.name}"/>
                                    </f:facet>
                                    <f:facet name="input">
                                        <h:inputText value="#{currentBottle.name}" style="width: 80%"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>
                            <p:column filterStyle="width: 80%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottletagslabel}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.tags}" converter="#{tagConverter}"/>
                                    </f:facet>
                                    <f:facet name="input">
                                        <h:inputText value="#{currentBottle.tags}" style="width: 80%"
                                                     converter="#{tagConverter}"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>
                            <p:column sortBy="#{currentBottle.quantity}"
                                      filterBy="#{currentBottle.quantity}"
                                      filterStyle="width: 80%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottlequantitylabel}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.quantity}"/>
                                    </f:facet>
                                    <f:facet name="input">

                                        <p:spinner value="#{currentBottle.quantity}"/>

                                    </f:facet>
                                </p:cellEditor>
                            </p:column>
                            <p:column sortBy="#{currentBottle.todrink}"
                                      filterBy="#{currentBottle.todrink}"
                                      filterStyle="width: 80%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottletodrinklabel}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.todrink}"><f:convertDateTime
                                                pattern="${messages.dateformat}"/> </h:outputText>
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:calendar value="#{currentBottle.todrink}"
                                                    pattern="${messages.dateformat}"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>
                            <p:column sortBy="#{currentBottle.acquired}"
                                      filterBy="#{currentBottle.acquired}"
                                      filterStyle="width: 80%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottleboughtlabel}">
                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.acquired}"> <f:convertDateTime
                                                pattern="dd/MM/yyyy"/> </h:outputText>
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:calendar value="#{currentBottle.acquired}"
                                                    pattern="${messages.dateformat}"/>
                                    </f:facet>
                                </p:cellEditor>
                            </p:column>
                            <p:column sortBy="#{currentBottle.producer.name}"
                                      filterBy="#{currentBottle.producer.name}"
                                      filterStyle="width: 90%"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottleproducerlabel}">
                                <h:outputText value="#{currentBottle.producer.name}"/>
                            </p:column>
                            <p:column sortBy="#{currentBottle.vintage}"
                                      filterStyle="width: 80%"
                                      filterBy="#{currentBottle.vintage}"
                                      filterMatchMode="contains"
                                      headerText="#{messages.bottlevintagelabel}">

                                <p:cellEditor>
                                    <f:facet name="output">
                                        <h:outputText value="#{currentBottle.vintage}"> </h:outputText>
                                    </f:facet>
                                    <f:facet name="input">
                                        <p:inputText value="#{currentBottle.vintage}"/>
                                    </f:facet>

                                </p:cellEditor>
                            </p:column>
                            <p:column headerText="Options">
                                <p:rowEditor/>
                                <p:commandLink ajax="false"
                                               actionListener="#{bottleManagedBean.delete(currentBottle)}"
                                               immediate="true"
                                               update="bottlesListPanel" process="@this">
                                    <span title="Remove" class="ui-icon ui-icon-trash"/>
                                </p:commandLink>
                            </p:column>
                        </p:dataTable>
                    </h:panelGroup>
                </h:panelGrid>
            </p:tab>

        </p:tabView>
    </h:form>
</ui:define>
</ui:composition>
</body>
</html>

src/main/webapp/protected/retreiveToken.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">
<body>
<ui:composition template="./standardtpl.xhtml">
    <ui:define name="content">
        <h:form prependId="false">
            <p>
                <p:commandLink actionListener="#{socialauthenticator.sendAuthorizationRequest}"
                               value="#{messages.tplgooglecalauthorization}"/>
            </p>
        </h:form>
    </ui:define>
</ui:composition>
</body>
</html>